#!/usr/bin/env php
<?php

#                                                          WHAT IS THIS FILE?
#                                                          ------------------
# This file is the main entry point for all Artisan commands. It is a simple wrapper around the
# Laravel framework that bootstraps the application and passes control to the Artisan console kernel.
#---------------------------------------------------------------------------------------
# TO SUMMARIZE, this file is the main command line interface we are going to use in our project
#---------------------------------------------------------------------------------------

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);


#!/usr/bin/env php
<?php

