<?php

namespace Database\Factories;

use App\Models\Category;
use App\Models\Post;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

/**
 * @extends Factory<Post>
 */
class PostFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */

    // =========================================================================================================================================================================
    //                                              This factory can be used to generate fake data for testing or seeding the database posts table.
    // =========================================================================================================================================================================
    public function definition(): array
    {
        $title = $this->faker->sentence;

        // The keys in the returned array correspond to the columns in the 'posts' table in the database
        // (The keys must match the column-names in the posts table)
        return [
            // The 'title' and 'content' fields are generated using the Faker library to create random sentences and paragraphs.
            'title' => $title,
            'content' => $this->faker->paragraph(),

            'slug' => Str::slug($title), // The 'slug' field is generated by converting the title into a URL-friendly format using the Str::slug() method.

            // The 'image' field is set to a random image URL, indicating that there is an image associated with the post by default.
            'image' => $this->faker->imageUrl(),

            // The 'category_id' field is set to a random existing category ID from the database, ensuring that each post is associated with a valid category.
            // Get Category model instances from database in random order. From that randomly ordered Category list, get the ID of first category.
            'category_id' => Category::inRandomOrder()->first()->id,

            'user_id' => User::inRandomOrder()->first()->id,

            'published_at' => $this->faker->optional()->dateTimeBetween('-1 years', 'now'), // Randomly set published_at to a date within the last year or leave it null
        ];
    }
}
